<!DOCTYPE html>
<html lang="hu">
    <head>

    </head>
    <body id="body">

        <h1>Skeleton</h1>

        <hr />
        <a href="<?=$this->url->get(['for' => 'frontend-index'])?>">Home</a> |
        <a href="<?=$this->url->get(['for' => 'frontend-testcache'])?>">Cache</a>
        <hr />

        <!-- flash -->
        <?=$this->flash->output()?>
        <!-- flash end -->

        <!-- content -->
        <div class="col-md-12">
            <?=$this->getContent() ?>
        </div>
        <!-- content end -->

    </body>
</html>
