<!doctype html>
<html lang="en" class="h-100">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="<?=$this->di->get('helper')->getAssetRevision('app.css', 'phalcon-skeleton')?>">
    <link rel="icon" type="image/x-icon" href="/favicon.ico">
    <title>Skeleton</title>
</head>

<body class="d-flex flex-column h-100">

<header>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
        <div class="container">
            <a class="navbar-brand" href="<?=$this->url->get(['for' => 'frontend-index'])?>">Skeleton</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="<?=$this->url->get(['for' => 'frontend-index'])?>">Home</a>
                    </li>
<?php if (in_array('test', $this->di->get('config')->application->modules->toArray())) : ?>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-bs-toggle="dropdown" aria-expanded="false">Test</a>
                        <ul class="dropdown-menu" aria-labelledby="dropdown01">
                            <li><a class="dropdown-item" href="<?=$this->url->get(['for' => 'test-cache-cache'])?>">Cache</a></li>
                            <li><a class="dropdown-item" href="<?=$this->url->get(['for' => 'test-log-log'])?>">Log</a></li>
                            <li><a class="dropdown-item" href="<?=$this->url->get(['for' => 'test-image-list'])?>">Image</a></li>
                            <li><a class="dropdown-item" href="<?=$this->url->get(['for' => 'test-filestorage-list'])?>">FileStorage</a></li>
                            <li><a class="dropdown-item" href="<?=$this->url->get(['for' => 'test-phpinfo-phpinfo'])?>">PHP info</a></li>
                            <li><a class="dropdown-item" href="<?=$this->url->get(['for' => 'test-xls-index'])?>">XLS</a></li>
                        </ul>
                    </li>
<?php endif; ?>
                </ul>
            </div>
            <span class="navbar-text">
<?php if ($this->di->get('config')->keycloak->enable === true) : ?>
                <?php if (empty($keycloakUser)) : ?>
                    <a href="<?=$this->url->get(['for' => 'frontend-keycloak-login'])?>" role="button" class="btn" title="Login">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                            <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
                            <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1"/>
                        </svg>
                    </a>
                <?php else : ?>
                    <a href="<?=$this->url->get(['for' => 'frontend-keycloak-logout'])?>" role="button" class="btn" title="Logout">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                            <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
                            <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1"/>
                        </svg>
                        <?=$keycloakUser['preferred_username']?>
                    </a>
                <?php endif; ?>
<?php endif; ?>
            </span>
        </div>
    </nav>
</header>

<main class="flex-shrink-0">
    <div class="container">

        <!-- flash -->
        <?=$this->flash->output()?>
        <!-- flash end -->

        <!-- content -->
        <div class="col-md-12">
            <?=$this->getContent() ?>
        </div>
        <!-- content end -->

    </div>
</main>

<footer class="footer mt-auto py-3 bg-light">
    <div class="container">
        <span class="text-muted">phalcon5-skeleton</span>
    </div>
</footer>

<script src="<?=$this->di->get('helper')->getAssetRevision('app.js', 'phalcon-skeleton')?>"></script>

</body>
</html>
